### ISSUE TITLE
- Stuff Todo -

### ISSUE THREAD

**Issue by u8sand** [u8sand/Baka-MPlayer#1]
General Issues
----
- [x] Dim desktop
  - [x] Window doesn't fill the screen on Ubuntu.
  - [x] Window covers screen on Windows.

Windows Specific Issues
----
- [ ] mpv's status message overlay is not shown (probably because we're missing lua)
- [x] @godly-devotion Quick Open button's image is kinda cropped out (doesn't happen with the playlist button).

Features
----
- [x] Mark the currently playing file in playlist
- [ ] OpenSubtitles.org integration
- [ ] Optional: after a file has finished playing (or played up to a certain percentage of the total duration), strike out the playlist item to show that they've watched it already.
  * As bonus, we can have an option that deletes the watched videos.
- [x] Tray icon
   - [x] Clicking the icon toggles play/pause (show popup saying Playing/Paused)
   - [ ] If opened file is an audio file, show pop up showing `{artist} - {title}` or just file name (without extension) if id3 info is not available. The Hide popup setting under preferences basically hides this popup if checked.

**Comment by mc4man** [comment]
It would be nice it the fullscreen controls where 'floating' rather than what is is now, ie the typical fs controller

**Comment by godly-devotion** [comment]
@mc4man: Not exactly sure what you mean. Could you elaborate?

**Comment by mc4man** [comment]
Typically in players when in fullscreen & cursor movement the control bar 'floats' over the vid. At least here the bar becomes part of the vid & causes a resize.

fullscreen, no controller bar - 
![screenshot from 2015-01-02 22 46 56](https://cloud.githubusercontent.com/assets/5961561/5601529/eed3d67a-92d2-11e4-95ab-dc6d975615a8.png)


fullscreen with controller bar - 
![screenshot from 2015-01-02 22 48 03](https://cloud.githubusercontent.com/assets/5961561/5601530/f86e6d9e-92d2-11e4-9b78-fd2c31f86b94.png)


Does this not happen to you guys?

**Comment by u8sand** [comment]
@mc4man This does happen and is intended. What we're not understanding is what you mean by "float over" if it just floats it'll block the video no?

**Comment by mc4man** [comment]
Well yeah, it would block or semi-block the small area it occupies while visible. Some player like vlc it's a bit translucent. From that perspective users expose the bar to use it so the fact it's there doesn't much matter
But you guys have a vision as to what you want so no big deal, just have never seen that before which doesn't necessarily mean it's bad.., just different.

**Comment by godly-devotion** [comment]
@mc4man @u8sand Well I'm going to delete these comments, if you want to further discuss this, please create a new issue. Thanks.

**Comment by u8sand** [comment]
Do this in workflowwy
